name: tektok
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  get: ^4.6.5
  get_storage: ^2.1.1
  logger: ^2.0.2+1
  jwt_decoder: ^2.0.1
  path_provider: ^2.1.2
  table_calendar: ^3.0.9
  google_fonts: 6.1.0
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_database: ^10.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/svg/
    - assets/images/gif/
    - assets/icons/
    - assets/icons/svg/