// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVp-dYHKUzY3VE0cYQFVjnfhn_iGhO7ag',
    appId: '1:770630620824:web:d8e11eccf5b08e6a70e2ed',
    messagingSenderId: '770630620824',
    projectId: 'tektok-9727e',
    authDomain: 'tektok-9727e.firebaseapp.com',
    databaseURL:
        'https://tektok-9727e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tektok-9727e.appspot.com',
    measurementId: 'G-8FJ6ELR2G0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs-HTgiYq6DSdEGH-PUz9rRp-MliBR24c',
    appId: '1:770630620824:android:7a9866d6554f8a8e70e2ed',
    messagingSenderId: '770630620824',
    projectId: 'tektok-9727e',
    databaseURL:
        'https://tektok-9727e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tektok-9727e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrnMzGPDdo2L-bzLZFWY7khsdZP94HgJw',
    appId: '1:770630620824:ios:1ac4dfc68d29d94970e2ed',
    messagingSenderId: '770630620824',
    projectId: 'tektok-9727e',
    databaseURL:
        'https://tektok-9727e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tektok-9727e.appspot.com',
    iosBundleId: 'com.either.tektok',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrnMzGPDdo2L-bzLZFWY7khsdZP94HgJw',
    appId: '1:770630620824:ios:1ac4dfc68d29d94970e2ed',
    messagingSenderId: '770630620824',
    projectId: 'tektok-9727e',
    databaseURL:
        'https://tektok-9727e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tektok-9727e.appspot.com',
    iosBundleId: 'com.either.tektok',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVp-dYHKUzY3VE0cYQFVjnfhn_iGhO7ag',
    appId: '1:770630620824:web:1fbaff59e636677b70e2ed',
    messagingSenderId: '770630620824',
    projectId: 'tektok-9727e',
    authDomain: 'tektok-9727e.firebaseapp.com',
    databaseURL:
        'https://tektok-9727e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tektok-9727e.appspot.com',
    measurementId: 'G-5GPDZTLJ19',
  );
}
